BookShop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('admin/', admin.site.urls),

    path('api/', include('Recipe.api.urls')),
    path('api/', include('Core.api.urls')),
    path('api/', include('Account.api.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path('', include('Core.urls')),
    path('', include('Story.urls')),
    path('', include('Account.urls')),
    path('', include('Recipe.urls')),
    path('', include('Order.urls')),
    path('api/', include('Order.api.urls')),
)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

Core/urls.py
from django.urls import path
from .views import ContactView, about, contact, index, user_profile

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('user_profile/', user_profile, name='user_profile'),
]

Recipe/urls.py
from django.urls import path
from .views import RecipeListViev


urlpatterns = [
    path('recipe_list/', RecipeListViev.as_view(), name='recipe_list'),
]

Story/urls.py
from django.urls import path
from Story.views import StoryList, StoryDetailView, story, story_detail


urlpatterns = [
    path('story_list/', StoryList.as_view(), name='story_list'),
    path('story_detail/<int:pk>', StoryDetailView.as_view(), name='story_detail'),
]

Recipe/models.py
from django.db import models
from Account.models import Account
from Story.models import Category, Tag


class Recipes(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='Recipe')
    content = models.TextField()
    show_date = models.DateField(null=True)

    tag = models.ManyToManyField(Tag)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='recipe_category')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

Story/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='Category/')

    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'


class Story(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='Story/') 
    description = models.TextField()

    tags = models.ManyToManyField(Tag)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='story_category')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    show_date = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'


class StoryComment(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Story Comment'
        verbose_name_plural = 'Story Comment'

Story/forms.py
from django import forms
from .models import StoryComment



class StoryCommentFormModel(forms.ModelForm):
    class Meta:
        model = StoryComment
        fields = ['message']

        labels = {
            'message' : 'Message'
        }

        widgets = {
            'message' : forms.Textarea(
                attrs={
                    'class' : 'form-control',
                    'rows' : 7,
                    'placeholder' :"Write your message"
                }
            ),
        }

Recipe/api/views.py
import django_filters.rest_framework
from rest_framework import filters
from rest_framework.views import APIView
from Recipe.api.pagination import LargePageNumberPagination, SmallPageNumberPagination
from Recipe.api.serializers import CategorySeralizers, RecipesCreateSerializers, RecipesReadSerializers
from Recipe.models import Recipes
from rest_framework.response import Response
from Story.models import Category
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated


class CategoryAPIView(APIView):

    def get(self, request, *args, **kwargs):

        categories = Category.objects.filter(is_active=True).all()
        serializers = CategorySeralizers(categories, context = {'request': request}, many=True)
        return Response(serializers.data)


class RecipeAPI(APIView):

    def get(self, request, *args, **kwargs):

        recipes = Recipes.objects.all()
        serializers = RecipesReadSerializers(recipes, context = {'request': request}, many=True)

        return Response(serializers.data)

    def post(self, request, *args, **kwargs):
        serializers = RecipesCreateSerializers(data=request.data, context={'request': request})

        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=201)
        return Response(serializers.errors, status=400)


class GenericAPIViewSerializerMixin:
    def get_serializer_class(self):
        return self.serializer_classes[self.request.method]


class RecipeListCreateAPI(GenericAPIViewSerializerMixin, ListCreateAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    # pagination_class = LargePageNumberPagination
    filter_backends = [django_filters.rest_framework.DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['tag', 'user', 'category']
    search_fields = ['title']
    ordering_fields = ['id', 'created_at']
    queryset = Recipes.objects.all()
    serializer_classes = {
        'GET' : RecipesReadSerializers,
        'POST' : RecipesCreateSerializers
    }


class RecipeRetrieveUpdateDestroyAPI(GenericAPIViewSerializerMixin, RetrieveUpdateDestroyAPIView):
    queryset = Recipes.objects.all()
    serializer_classes = {
        'GET' : RecipesReadSerializers,
        'PUT' : RecipesCreateSerializers,
        'PATCH' : RecipesCreateSerializers
    }


class RecipeReadUpdateDeleteView(APIView):

    def get(self, request, *args, **kwargs):
        id = kwargs['pk']
        recipe = Recipes.objects.get(id=id)
        serializer = RecipesReadSerializers(recipe)
        return Response(serializer.data, status=200)

    def put(self, request, *args, **kwargs):
        id = kwargs['pk']
        recipe = Recipes.objects.get(id=id)
        recipe_data = request.data
        serializer = RecipesCreateSerializers(data=recipe_data, instance=recipe)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=200)

    def patch(self, request, *args, **kwargs):
        id = kwargs['pk']
        recipe = Recipes.objects.get(id=id)
        recipe_data = request.data
        serializer = RecipesCreateSerializers(data=recipe_data, partial=True, instance=recipe)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=200)

    def delete(self, request, *args, **kwargs):
        id = kwargs['pk']
        recipe = Recipes.objects.get(id=id)
        recipe.delete()
        return Response(status=204)

Recipe/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Category
from .models import Recipes
from datetime import datetime





class RecipeListViev(ListView):
    model = Recipes
    template_name = 'recipes.html'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categories"] = Category.objects.filter(is_active=True).all()

        return context
    

    def get_queryset(self):

        current_time = datetime.now().date()

        ctg = self.request.GET.get('ctg')

        if ctg:
            self.queryset = Recipes.objects.filter(category__id=ctg,category__is_active=True, show_date__lte=current_time).all()
        else:
            self.queryset = Recipes.objects.filter(category__is_active=True, show_date__lte=current_time).all()

        return super().get_queryset()

Story/views.py
from django.shortcuts import redirect, render
from Story.forms import StoryCommentFormModel
from .models import Category, Story, StoryComment, Tag
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView
from django.contrib import messages


def story(request):

    q_category = request.GET.get('category')

    print('==>', request.GET)

    categories = Category.objects.exclude(is_active=False).all()

    if q_category:
        stories = Story.objects.filter(category__id=q_category, category__is_active=True, show_date__lte=datetime.date(datetime.now())).all()
    else:
        stories = Story.objects.filter(category__is_active=True, show_date__lte=datetime.date(datetime.now())).all()


    context = {
        'stories': stories,
        'categories': categories,
    }

    return render(request, 'story.html', context)


class StoryList(ListView):
    model = Story
    template_name = 'story.html'
    context_object_name = 'stories'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categories"] = Category.objects.exclude(is_active=False).all()

        return context

    def get_queryset(self):

        category = self.request.GET.get('category')

        if category:
            self.queryset = Story.objects.filter(category__id=category, category__is_active=True, show_date__lte=datetime.date(datetime.now())).all()
        else:
            self.queryset = Story.objects.filter(category__is_active=True, show_date__lte=datetime.date(datetime.now())).all()

        return super().get_queryset()


class StoryDetailView(DetailView, CreateView):
    model = Story
    template_name = 'single.html'
    form_class = StoryCommentFormModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.filter(is_active=True).all()
        context['tags'] = Tag.objects.all()
        context['story_comments'] = StoryComment.objects.all()

        return context

    def form_valid(self, form, *args, **kwargs):
        # form.instance.story = Story.objects.get(pk = self.kwargs.get('pk'))
        form.instance.story = self.get_object()
        form.instance.user = self.request.user
        form.instance.save()
        messages.success(self.request, 'Story comment submit oldu')

        return redirect("story_detail", pk = self.kwargs.get('pk'))




@login_required
def story_detail(request, id):

    story = Story.objects.filter(id=id, category__is_active = True).first()

    if not story:
        return redirect('story_list')


    tags = Tag.objects.all()

    categories = Category.objects.filter(is_active=True).all()

    context = {
        'story' : story,
        'tags' : tags,
        'categories' : categories
    }

    return render(request, 'single.html', context)

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="100">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include "subscribe.html" %}

{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>FOODDDD</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static '' %}css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="{% static '' %}css/animate.css">

    <link rel="stylesheet" href="{% static '' %}css/owl.carousel.min.css">
    <link rel="stylesheet" href="{% static '' %}css/owl.theme.default.min.css">
    <link rel="stylesheet" href="{% static '' %}css/magnific-popup.css">

    <link rel="stylesheet" href="{% static '' %}css/aos.css">

    <link rel="stylesheet" href="{% static '' %}css/ionicons.min.css">

    <link rel="stylesheet" href="{% static '' %}css/flaticon.css">
    <link rel="stylesheet" href="{% static '' %}css/icomoon.css">
    <link rel="stylesheet" href="{% static '' %}css/style.css">

    {% block css %}

    {% endblock %}


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">
            {% if user.is_authenticated %}{{ user.get_full_name }}{% else %}Stories{% endif %}
            <span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="index.html" class="nav-link">{% trans "Home" %}</a></li>
                <li class="nav-item active"><a href="{% url 'about' %}" class="nav-link">{% trans "About" %}</a></li>
                <li class="nav-item"><a href="{% url 'story_list' %}" class="nav-link">{% trans "Stories" %}</a></li>
                <li class="nav-item"><a href="{% url 'recipe_list' %}" class="nav-link">{% trans "Recipes" %}</a></li>
                <li class="nav-item"><a href="contact.html" class="nav-link">{% trans "Contact" %}</a></li>

                {% get_current_language as CURRENT_LANGUAGE %}
                {% get_available_languages as AVAILABLE_LANGUAGES %}
                {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}

                <div class="languages">
                    <ul class="languages">
                        {% for language in languages %}
                        <li>
                            <a href="/{{ language.code }}/"
                            {% if language.code == CURRENT_LANGUAGE %} class="active"{% endif %}>
                            {{ language.name_local }} {{ language.code }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="btn btn-black px-3 px-md-4 py-3">{% trans "Log Out" %}</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}" class="btn btn-black px-3 px-md-4 py-3">{% trans "Log In" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

{% block content %}

{% endblock %}

<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="{% static '' %}js/jquery.min.js"></script>
<script src="{% static '' %}js/jquery-migrate-3.0.1.min.js"></script>
<script src="{% static '' %}js/popper.min.js"></script>
<script src="{% static '' %}js/bootstrap.min.js"></script>
<script src="{% static '' %}js/jquery.easing.1.3.js"></script>
<script src="{% static '' %}js/jquery.waypoints.min.js"></script>
<script src="{% static '' %}js/jquery.stellar.min.js"></script>
<script src="{% static '' %}js/owl.carousel.min.js"></script>
<script src="{% static '' %}js/jquery.magnific-popup.min.js"></script>
<script src="{% static '' %}js/aos.js"></script>
<script src="{% static '' %}js/jquery.animateNumber.min.js"></script>
<script src="{% static '' %}js/scrollax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static '' %}js/google-map.js"></script>
<script src="{% static '' %}js/main.js"></script>

</body>
</html>

templates/recipes.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Recipes</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Recipes <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">

                    {% for recipe in recipes_list %}
                        <div class="col-md-6 col-lg-12 ftco-animate">
                            <div class="blog-entry d-lg-flex">
                                <div class="half">
                                    <a href="single.html" class="img d-flex align-items-end"
                                    style="background-image: url({{ recipe.image.url }});">
                                        <div class="overlay"></div>
                                    </a>
                                </div>
                                <div class="text px-md-4 px-lg-5 half pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{ recipe.category.name|capfirst }}</span><span class="ml-auto pl-3">{{ recipe.show_date|date:"Y-N-d" }}</span>
                                    </p>
                                    <h3><a href="single.html">{{ recipe.title|capfirst }}</a></h3>
                                    <p>{{ recipe.content|truncatewords:25 }}</p>
                                    <p class="mb-0"><a href="single.html" class="btn btn-primary">Read More <span
                                            class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% endif %}

                                {% for page in paginator.page_range %}
                                    {% if page_obj.number == page %}
                                        <li class="active"><a href="?page={{ page }}"><span>{{ page }}</span></a></li>
                                    {% else %}
                                        <li><a href="?page={{ page }}"><span>{{ page }}</span></a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{% static '' %}images/author.jpg" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the
                                countries Vokalia and Consonantia, there live the blind texts. Separated they live in
                                Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        </div>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" name="recipe" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box categories text-center ftco-animate">
                        <h2 class="heading mb-4">Categories</h2>
                        <ul class="category-image">

                            {% for ctg in categories %}
                                <li>
                                    <a href="{% url 'recipe_list' %}?ctg={{ ctg.id }}" class="img d-flex align-items-center justify-content-center text-center"
                                    style="background-image: url({{ ctg.image.url }});">
                                        <div class="text">
                                            <h3>{{ ctg.name|capfirst }}</h3>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include "subscribe.html" %}

{% endblock %}

templates/subscribe.html
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>